/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thammachart' at '11/28/16 7:27 PM' with Gradle 3.2.1
 *
 * @author thammachart, @date 11/28/16 7:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
